version: "3"
services:
  node-app:
    container_name: node-app
    build: .
    ports:
      - "3000:4000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
#    environment:
#      - PORT=4000  